language: node_js
sudo: false
node_js:
  - '0.12'
  - 'stable'
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE database;' -U postgres
  - psql -c 'CREATE USER username WITH PASSWORD "password"' -U postgres
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
